Repository mhatzl/web_ids, pull requests merged in 2021-05, with the labels that each got.

#6 Signature files reading modified as requested. Basic matching implemented.
  lib/web_ids.js
Labels: enhancement

#10 fix-log-consistency
  doc/FetchingLogs.md
  lib/web_ids.js
Labels: enhancement

#16 Fix matching and typo in checkRequest
  lib/web_ids.js
Labels: bug

#14 Changes to signatures
  doc/README.md
  doc/Signatures.md
  signatures/example_signatures.json
  signatures/signatures.json
  signatures/signatures_1.json
Labels: documentation
